In [2]:
import torch.nn as nn
import torch
import pandas as pd
import datetime

In [7]:
adj = torch.Tensor([[1,2],[3,4]])

ret = torch.topk(adj, k=1)
res = torch.zeros_like(adj)
res.scatter_(1, ret.indices, ret.values)
res


tensor([[0., 2.],
        [0., 4.]])

In [10]:

df = pd.read_hdf('data/LCL_12month.h5').iloc[:,:10]
len(df.index)

17472

In [11]:

df.index = pd.to_datetime(df.index)
df_one_month = df[df.index < datetime.datetime(2013,2,1,0,0,0)]
len(df_one_month.index)

1487

In [5]:
y = x.transpose(0,1)
y.stride()

(2, 6, 1)

In [14]:
x

tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

In [11]:
y.shape

torch.Size([3, 2, 2])

In [13]:
y

tensor([[[ 1,  2],
         [ 7,  8]],

        [[ 3,  4],
         [ 9, 10]],

        [[ 5,  6],
         [11, 12]]])

In [7]:
z = y.contiguous()
z.stride()

(4, 2, 1)

In [10]:
z.shape

torch.Size([3, 2, 2])

In [44]:
import numpy as np
def convert(s: str, numRows: int) -> str:
        if numRows == 1:
            return s
        n_blocks = len(s) // (2*numRows - 2)
        residue = len(s) % (2*numRows - 2)
        extra_cols = 1 if residue <= numRows else 1 + residue - numRows
        n_cols = n_blocks*(numRows - 1) + extra_cols

        table = [[""] * int(n_cols)] * numRows 
        # table = np.array(table)
        for i, c in enumerate(s):
            block = i // (2 * numRows - 2)
            res = i % (2 * numRows - 2)
            row = res if res < numRows else 2*numRows - 2 - res
            col = block * (numRows - 1) if res < numRows else block * (numRows - 1) + res - numRows + 1
            print(table[row][col])
            table[row][col] = c
            

        result = ""
        for row in range(len(table)):
            for col in range(len(table[row])):
                result += table[row][col]
        return result
convert('PAYPALISHIRING', 3)


P
A


A
L


H
I


N


'YPISRIGYPISRIGYPISRIG'

In [22]:
# power-2 pool of window of length 3, with stride 2.
m = nn.LPPool1d(2, 3, stride=2)
input = torch.randn(2, 2, 20)
output = m(input)
output.shape

torch.Size([2, 2, 9])

In [1]:
import pandas as pd

In [2]:
df = pd.read_hdf('data/LCL_12month.h5')

In [7]:
df.iloc[:,:20]

MAC000002  MAC000003  MAC000005  MAC000007  MAC000009  \
1357000200000000000      0.241      1.922      0.111      0.204      0.176   
1357002000000000000      0.191      1.808      0.071      0.161      0.147   
1357003800000000000      0.235      0.795      0.035      0.214      0.093   
1357005600000000000      0.182      1.235      0.035      0.186      0.088   
1357007400000000000      0.229      0.924      0.034      0.126      0.145   
...                        ...        ...        ...        ...        ...   
1388440800000000000      0.424      0.080      0.297      0.390      0.286   
1388442600000000000      0.477      0.093      0.113      0.872      0.209   
1388444400000000000      0.445      0.107      0.113      0.279      0.285   
1388446200000000000      0.433      0.097      0.104      0.230      0.114   
1388448000000000000      0.461      1.394      0.040      0.087      0.078   

                     MAC000010  MAC000011  MAC000013  MAC000014  MAC000017  \
1357000200000000000      0.453      0.301      0.349      0.034      0.040   
1357002000000000000      0.500      0.657      0.284      0.033      0.077   
1357003800000000000      0.621      0.683      0.136      0.016      0.035   
1357005600000000000      0.197      0.658      0.140      0.034      0.035   
1357007400000000000      0.176      0.773      0.102      0.026      0.071   
...                        ...        ...        ...        ...        ...   
1388440800000000000      1.980      0.348      0.109      0.114      0.158   
1388442600000000000      1.120      0.309      0.070      0.149      0.207   
1388444400000000000      1.625      0.329      0.110      0.120      0.174   
1388446200000000000      0.856      0.270      0.129      0.123      0.194   
1388448000000000000      0.480      0.308      0.090      0.048      0.181   

                     MAC000018  MAC000019  MAC000020  MAC000021  MAC000022  \
1357000200000000000      0.191      0.087      0.080      0.386      0.479   
1357002000000000000      0.131      0.116      0.063      0.331      0.472   
1357003800000000000      0.146      0.069      0.074      0.398      0.473   
1357005600000000000      0.115      0.109      0.052      0.529      0.464   
1357007400000000000      0.142      0.068      0.058      0.392      0.379   
...                        ...        ...        ...        ...        ...   
1388440800000000000      0.567      0.207      0.240      1.149      0.518   
1388442600000000000      0.577      0.198      0.225      1.001      0.474   
1388444400000000000      0.271      0.180      0.232      0.992      0.495   
1388446200000000000      0.324      0.101      0.183      0.881      0.506   
1388448000000000000      0.262      0.075      0.189      0.470      0.526   

                     MAC000023  MAC000024  MAC000026  MAC000027  MAC000030  
1357000200000000000      0.040      2.856      0.131      0.218      0.065  
1357002000000000000      0.049      2.830      0.165      0.379      0.145  
1357003800000000000      0.143      2.870      0.163      0.215      0.128  
1357005600000000000      0.380      3.324      0.131      0.254      0.058  
1357007400000000000      0.094      2.810      0.130      0.196      0.094  
...                        ...        ...        ...        ...        ...  
1388440800000000000      0.559      1.377      0.133      0.300      0.164  
1388442600000000000      0.543      1.276      0.114      0.183      0.197  
1388444400000000000      0.515      1.071      0.142      0.194      0.187  
1388446200000000000      0.480      1.187      0.121      0.266      0.065  
1388448000000000000      0.195      1.245      0.098      0.261      0.098  

[17472 rows x 20 columns]

In [ ]:
corpus = litstudy.build_corpus(docs, ngram_threshold=0.8)